### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by csbanda** [zuri-training/pjt-28-price-compare-shopsmart#13]
Task completed

**Comment by ifylyd** [comment]
I coded this design

**Comment by Favourwendee** [comment]
I added High-fi design 
[https://www.figma.com/file/P9UFnIxyfuvMkKNkKUWh76/Team-28_Price-Compare?node-id=454%3A102](url)

**Comment by Dev-180Memes** [comment]
I built and implemented the backend for this
