### ISSUE TITLE
(Brand) Hp and Lenovo Page

### ISSUE THREAD

**Issue by csbanda** [zuri-training/pjt-28-price-compare-shopsmart#23]
To be completed

**Comment by ifylyd** [comment]
Low fi design have been coded

**Comment by samsobocreations** [comment]
I made little  readjustments

**Comment by Favourwendee** [comment]
I added high-fi design to the pages

**Comment by Favourwendee** [comment]
[https://www.figma.com/file/P9UFnIxyfuvMkKNkKUWh76/Team-28_Price-Compare?node-id=454%3A102](url)
