### ISSUE TITLE
Designed Dashboard high-fi menu pages

### ISSUE THREAD

**Issue by csbanda** [zuri-training/pjt-28-price-compare-shopsmart#29]
Completed

**Comment by Favourwendee** [comment]
The following dashboard high fi design was done by me
1. My Reviews
2. My profile
3. My alert
4. My history

**Comment by Juannyn** [comment]
I. designed the Lo-fi and High_fi of the Dashboard which contains;

1. My profile
2. My review
3. My watchlist
4. My history and
5. My alerts
