### ISSUE TITLE
Sign in Page

### ISSUE THREAD

**Issue by csbanda** [zuri-training/pjt-28-price-compare-shopsmart#3]
Wireframe and Lofi Completed

**Comment by Favourwendee** [comment]
Added High fi design to the Sign in page
[https://www.figma.com/file/P9UFnIxyfuvMkKNkKUWh76/Team-28_Price-Compare?node-id=454%3A102](url)

**Comment by csbanda** [comment]
[Personal contribution to the design]

https://www.figma.com/file/rbEp5SbNKIRyohVPL5NbpH/Chiluba's-Design-File_Team_28_Contribution?node-id=0%3A1
