### ISSUE TITLE
Research Plan and user interviews

### ISSUE THREAD

**Issue by csbanda** [zuri-training/pjt-28-price-compare-shopsmart#5]
Completed

**Comment by vohkehosusuluwa** [comment]
To understand who our users are and their painpoints,I drafted research questions which were also infused into the questionairre

**Comment by csbanda** [comment]
Task https://docs.google.com/document/d/1PhX7qXVN5obu5mwS0V_I3C9kC7J1HecM/edit?usp=sharing&ouid=111153273306898484740&rtpof=true&sd=truecompleted

**Comment by csbanda** [comment]
[Personal contribution link to the task](https://docs.google.com/document/d/18rf5kubo9qFkFgK315FLb0AQYiUn9I4F/edit?usp=sharing&ouid=111153273306898484740&rtpof=true&sd=true)
